Migration script, makefile, readme, github actions
drmaxgit/drmax-gitlab-azdo-migration pull request #1
Opened 2022-02-07 19:01 UTC by klatys

2022-02-07 19:16 UTC, marley-ma approved these changes

2022-02-11 13:29 UTC, skooda approved these changes
Minor suggestions.

2022-02-11 13:29 UTC, skooda commented on main.go
> +			if mr.State == "closed" || mr.State == "merged" {
Could be flatter... (separate functions)

2022-02-11 13:29 UTC, skooda commented on main.go
> +				continue
Not sure what is content of err API response, but adding a ProjectName and other metadata to logged error would be great, for later investigation.

2022-02-11 15:49 UTC, klatys commented on main.go
> +			if mr.State == "closed" || mr.State == "merged" {
valid, thanks! Refactored

2022-02-11 15:50 UTC, klatys commented on main.go
> +				continue
valid, thanks! expanded the logging

2022-02-16 22:46 UTC, marley-ma requested changes
Nothing against the implementation itself but I'm little bit worried about the error handling approach which is introducing a mixture of different approaches from explicitly ignored errors to mixing of error return as log.error and nil state to higher level with log.fatal which leads to process.exit and it is introducing different behavior on different execution unit levels. This should be serialized to unified approach.

Once suggested error handling will be refactore I'd ask for splliting of some methods especially those whos having several isolated if conditions and for cycle - especially translateDiscussion and importRepository functions.

Have you considered some unit tests for the key parts where some manipulation take place?

What about the SRP code isolation into the separate files based on logical context?

2022-02-18 11:12 UTC, klatys commented
@marley-ma refactored to flatten the logic into separate functions and covered with tests where applicable.
As for the logging, to an extent I agree:
- I've added log of some previously ommited errors  in 6d598c77d1307befc212112400dba2861204c71e
- As for different approaches I don't think that error handling can/should be super unified:
  - where the error causes inability to run the script it's okay to raise the error and panic out (three places in this case - config read, both clients init)
  - where the error doesn't necessarily cause/call for a full break it's just logged and usually in the place where this happens - after all this is not SDK/Library where it actually makes sense to pass the errors upwards, here it would IMO harden the readability as you're just passing the errors higher and logging there anyway

2022-02-28 14:34 UTC, mrlm-xyz approved these changes

2022-03-03 10:46 UTC, merged